#!/usr/bin/env node

const http = require('http')

const port = ~~process.env.PORT

http.createServer((req, res) => {
  if (Math.random() > .90) {
    res.statusCode = 500 + (Math.random() * 15 | 0)
    res.end('5xx error')
    return
  }

  if (Math.random() > .75) {
    res.statusCode = 400 + (Math.random() * 15 | 0)
    res.end('4xx error')
    return
  }

  res.end('ok')
}).listen(port, '127.0.0.1')
