#!/usr/bin/env node

const http = require('http')

const port = ~~process.env.PORT
const region = process.env.AWS_REGION

http.createServer((req, res) => {
  res.end('Hello from '+region+'\n')
}).listen(port, '127.0.0.1')
